# Generated by Django 2.1.3 on 2019-10-27 08:04

from django.db import migrations, models
import django.db.models.deletion
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_bc_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Creator Blockchain Address')),
                ('problem_endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Problem Endpoint URL')),
                ('problem_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Problem Object Storage Key')),
                ('problem_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Problem Object Storage Secret')),
                ('solution_endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solution Endpoint URL')),
                ('solution_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solution Object Storage Key')),
                ('solution_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solution Object Storage Secret')),
                ('approver_bc_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approver Blockchain Address')),
                ('assigned', models.BooleanField(default=False, verbose_name='Assigned to Educator?')),
                ('assessed', models.BooleanField(default=False, verbose_name='Assessed by Educator?')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved by Educator?')),
                ('grade', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eight'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelth')], max_length=2, null=True, verbose_name='Grade Level')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Educator Comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('static_problem_photo', models.ImageField(blank=True, null=True, upload_to=edu.models.get_static_problem_path, verbose_name='Static Problem Photo')),
                ('static_solution_photo', models.ImageField(blank=True, null=True, upload_to=edu.models.get_static_solution_path, verbose_name='Static Solution Photo')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Educator')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
    ]
