# Generated by Django 2.1.3 on 2019-10-27 08:06

from django.db import migrations, models
import django.db.models.deletion
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_tutorproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer_bc_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answerer Blockchain Address')),
                ('answerer_endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer Endpoint URL')),
                ('answerer_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer Object Storage Key')),
                ('answerer_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer Object Storage Secret')),
                ('approver_bc_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approver Blockchain Address')),
                ('assigned', models.BooleanField(blank=True, default=False, null=True, verbose_name='Assigned to Educator?')),
                ('assessed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Assessed by Educator?')),
                ('approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='Approved by Educator?')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct According to Educator?')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Educator Comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('static_answer_photo', models.ImageField(blank=True, null=True, upload_to=edu.models.get_static_answer_path, verbose_name='Static Answer Photo')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Educator')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tutor_Problem', to='edu.TutorProblem')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_grade', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eight'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelth')], max_length=2, null=True, verbose_name='Tutor Grade at Time')),
                ('tutee_grade', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eight'), ('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelth')], max_length=2, null=True, verbose_name='Tutee Grade at Time')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('assigned', models.BooleanField(default=False, verbose_name='Assigned to Educator?')),
                ('assessed', models.BooleanField(default=False, verbose_name='Assessed by Educator?')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved by Educator?')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Educator Comments')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Educator')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TutoringSession_Tutee', to='edu.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TutoringSession_Tutor', to='edu.Student')),
            ],
        ),
    ]
