# Generated by Django 2.1.3 on 2019-10-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_tuteeanswer_tutoringsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('info', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Info')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Educator')),
            ],
        ),
        migrations.CreateModel(
            name='BadgesEarned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TuteeAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.TuteeAnswer')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.TutoringSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TutorProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.TutorProblem')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Student')),
            ],
        ),
    ]
