# Generated by Django 2.1.3 on 2019-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_badge_badgesearned_coursesattended_tuteeanswers_tutoringsessions_tutorproblems'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='edu.CoursesAttended', to='edu.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.ManyToManyField(related_name='Badges_Earned', through='edu.BadgesEarned', to='edu.Badge'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_attended',
            field=models.ManyToManyField(related_name='Courses_Attended', through='edu.CoursesAttended', to='edu.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutee_answers',
            field=models.ManyToManyField(related_name='Tutee_Answers', through='edu.TuteeAnswers', to='edu.TuteeAnswer'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutor_problems',
            field=models.ManyToManyField(related_name='Tutor_Problems', through='edu.TutorProblems', to='edu.TutorProblem'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutoring_sessions',
            field=models.ManyToManyField(related_name='Tutoring_Sessions', through='edu.TutoringSessions', to='edu.TutoringSession'),
        ),
    ]
