# Generated by Django 2.1.3 on 2019-10-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Blog Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('body', models.TextField(verbose_name='Blog Body')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date-time Posted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog_Category', to='main.BlogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='Carousel Index')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_carousel_image_path, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('address', models.CharField(max_length=100, verbose_name='Event Address')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('cost', models.CharField(max_length=30, verbose_name='Cost')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_event_image_path, verbose_name='Event Image')),
                ('attendees', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, choices=[('vball-top-level', 'Volleyball - Top Level Page Header'), ('vball-top-level2', 'Volleyball - Top Level Page Header 2nd'), ('vball-top-level3', 'Volleyball - Top Level Page Header 3rd'), ('vball-top-level4', 'Volleyball - Top Level Page Header 4th'), ('vball-top-level5', 'Volleyball - Top Level Page Header 5th'), ('pball-top-level', 'Pickleball - Top Level Page Header'), ('pball-top-level2', 'Pickleball - Top Level Page Header 2nd'), ('pball-top-level3', 'Pickleball - Top Level Page Header 3rd'), ('pball-top-level4', 'Pickleball - Top Level Page Header 4th'), ('pball-top-level5', 'Pickleball - Top Level Page Header 5th'), ('sports-top-level', 'Sports - Top Level Page Header')], max_length=100, null=True, unique=True, verbose_name='Photo Tag')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Photo Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_site_photo_image_path, verbose_name='Image File')),
                ('max_width', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=main.models.get_user_profile_image_path, verbose_name='Profile Photo')),
                ('asked_fb', models.BooleanField(default=False, verbose_name='Asked about Facebook?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
